apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: padel-dev
type: Opaque
stringData: # Change these values in your local environment before applying to the cluster
# In a real production environment, you should use a more secure method to manage secrets, such as Azure Key Vault, AWS Secrets Manager, or HashiCorp Vault.
  USER_DB_PASSWORD: "changeme123"
  COURT_DB_PASSWORD: "changeme123"
  BOOKING_DB_PASSWORD: "changeme123"
  JWT_SECRET: "clave-super-secreta-para-tokens"